name: First-Time Contributor Bot

on:
  pull_request:
    types: [opened]

jobs:
  welcome_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Debug Token
        run: echo "Token is set: ${{ secrets.PAT_TOKEN != '' }}"
        
      - name: Run the First-Time Contributor Bot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_NAME: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python scripts/first.py
